project:
  type: website
  output-dir: docs

website:
  open-graph: true
  search: false
  title: "Uiro"
  #cookie-consent: true

  page-navigation: true
  
  page-footer: 
    left: "&copy; 2024 Uiro.io" 
    right: 
      - icon: instagram
        href: https://www.instagram.com/uiro.io/?igsh=NjhvbWo4Z2c0NDF5

  navbar:
    right:
      - text: "Veja nossas análises"
        href: analises.qmd
      - text: 'Sobre'
        menu:
          - text: 'Equipe'
            href: equipe.qmd
          #- text: 'Manifesto'
          #  href: manifesto.qmd
      - text: "Feedbacks"
        href: clientes.qmd
      - text: 'Contato'
        href: contato.qmd

format:
  html:
    theme:
      dark: lux
    css: styles.css
    toc: true

editor: visual

